linters-settings:
  custom:
    # 2020-07-13 @anorth disabled, local build failing with "Unable to load custom analyzer nomaprange:.nomaprange.so, plugin: not implemented"
    #nomaprange:
    #  path: .nomaprange.so
    #  description: Checks for range over maps
    #  original-url: github.com/Kubuxu/go-no-map-range

linters:
  enable:
    #- nomaprange

run:
  skip-dirs-use-default: false

issues:
  exclude-rules:
    - path: _test\.go
      text: "range iteration over map"
